---
title: "Homework 05"
subtitle: "Causal Inference"
author: "Name"
date: "October 15, 2019"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.width="0.9\\linewidth",dev="pdf",fig.align  = 'center')
pacman::p_load("ggplot2","knitr","faraway","arm","hett","data.table","foreign","car","VGAM","MASS")
```


## Design of an experiment 
1. Suppose you are interested in the effect of the presence of vending machines in schools on childhood obesity. What randomized experiment would you want to do (in a perfect world) to evaluate this question?
 
2. Suppose you are interested in the effect of smoking on lung cancer. What randomized experiment could you plausibly perform (in the real world) to evaluate this effect?

3. Suppose you are a consultant for a researcher who is interested in investigating the effects of teacher quality on student test scores. Use the strategy of mapping this question to a randomized experiment to help define the question more clearly. Write a memo to the researcher asking for needed clarifications to this study proposal.

## Causal effect
The table below describes a hypothetical experiment on 2400 persons. Each row of the table specifies a category of person, as defined by his or her pre-treatment predictor $x$, treatment indicator $T$ , and potential outcomes $y_0$, $y_1$. (For simplicity, we assume unrealistically that all the people in this experiment fit into these eight categories.)

Category | $\#$ persons in category | $x$   | $T$   | $y_0$  |$y_1$  |
---------|--------------------------|-------|-------|--------|-------|
1        |                    300   |   0   |   0   |    4   |   6 
2        |                    300   |   1   |   0   |    4   |   6 
3        |                    500   |   0   |   1   |    4   |   6 
4        |                    500   |   1   |   1   |    4   |   6 
5        |                    200   |   0   |   0   |   10   |   12 
6        |                    200   |   1   |   0   |   10   |   12 
7        |                    200   |   0   |   1   |   10   |   12 
8        |                    200   |   1   |   1   |   10   |   12

In making the table we are assuming omniscience, so that we know both $y_0$ and $y_1$ for all observations. But the (nonomniscient) investigator would only observe $x$, $T$, and $y^T$ for each unit. (For example, a person in category 1 would have $x=0$,$T =0$,$y=4$, and a person in category 3 would have $x=0$,$T =1$,$y=6$.)

(a) What is the average treatment effect in this population of 2400 persons?
(b) Is it plausible to believe that these data came from a randomized experiment?
Defend your answer.
(c) Another population quantity is the mean of $y$ for those who received the
treatment minus the mean of $y$ for those who did not. What is the relation
between this quantity and the average treatment effect?
(d) For these data, is it plausible to believe that treatment assignment is ignorable
given sex? Defend your answer.

(e)  Figure out the estimate and the standard error of the coefficient of $T$ in a regression of $y$ on $T$ and $x$.

## Consulting
You are consulting for a researcher who has performed a randomized trial where the treatment was a series of 26 weekly therapy sessions, the control was no therapy, and the outcome was self-report of emotional state one year later. However, most people in the treatment group did not attend every therapy session. In fact there was a good deal of variation in the number of therapy sessions actually attended. The researcher is concerned that her results represent "watered down" estimates because of this variation and suggests adding in another predictor to the model: number of therapy sessions attended. What would you advise her?

## Gain-score models:
In the discussion of gain-score models in [GH] Section 9.3, we noted that if we include the pre-treatment measure of the outcome in a gain score model, the coefficient on the treatment indicator will be the same as if we had just run a standard regression of the outcome on the treatment indicator and the pre-treatment measure. Show why this is true.

## linear regression
Assume that linear regression is appropriate for the regression of an outcome, $y$, on treatment indicator, $T$, and a single confounding covariate, $x$. Sketch hypothetical data (plotting $y$ versus $x$, with treated and control units indicated by circles and dots, respectively) and regression lines (for treatment and control group) that represent each of the following situations:
a. No treatment effect,
b. Constant treatment effect,
c. Treatment effect increasing with $x$.

## Hypothetical Study
Consider a study with an outcome, $y$, a treatment indicator, $T$ , and a single confounding covariate, $x$. Draw a scatterplot of treatment and control observations that demonstrates each of the following:
(a) A scenario where the difference in means estimate would not capture the true treatment effect but a regression of $y$ on $x$ and $T$ would yield the correct estimate.
(b) A scenario where a linear regression would yield the wrong estimate but a nonlinear regression would yield the correct estimate.

## Messy randomization
The folder `cows` contains data from an agricultural experiment that was conducted on 50 cows to estimate the effect of a feed additive on six outcomes related to the amount of milk fat produced by each cow.  

Four diets (treatments) were considered, corresponding to different levels of the additive, and three variables were recorded before treatment assignment: lactation number (seasons of lactation), age, and initial weight of cow.

Cows were initially assigned to treatments completely at random, and then the distributions of the three covariates were checked for balance across the treat- ment groups; several randomizations were tried, and the one that produced the "best"balance with respect to the three covariates was chosen. The treatment assignment is ignorable (because it depends only on fully observed covariates and not on unrecorded variables such as the physical appearances of the cows or the times at which the cows entered the study) but unknown (because the decisions whether to rerandomize are not explained).
We shall consider different estimates of the effect of additive on the mean daily milk fat produced.
a. Consider the simple regression of mean daily milk fat on the level of additive. Compute the estimated treatment effect and standard error, and explain why this is not a completely appropriate analysis given the randomization used.
b. Add more predictors to the model. Explain your choice of which variables to include. Compare your estimated treatment effect to the result from (a).
c. Repeat (b), this time considering additive level as a categorical predictor
with four letters. Make a plot showing the estimate (and standard error) of the treatment effect at each level, and also showing the inference the model fit in part (b).

## sesame
The folder `sesame` contains data from an experiment in which a randomly selected group of children was encouraged to watch the television program Sesame Street and the randomly selected control group was not.
a. The goal of the experiment was to estimate the effect on child cognitive devel- opment of watching more Sesame Street. In the experiment, encouragement but not actual watching was randomized. Briefly explain why you think this was done. (Hint: think of practical as well as statistical reasons.)
b. Suppose that the investigators instead had decided to test the effectiveness of the program simply by examining how test scores changed from before the intervention to after. What assumption would be required for this to be an appropriate causal inference? Use data on just the control group from this study to examine how realistic this assumption would have been.
c. Did encouragement (the variable viewenc in the dataset) lead to an increase in post-test scores for letters (postlet) and numbers (postnumb)? Fit an appropriate model to answer this question.
d. We are actually more interested in the effect of watching Sesame Street regu- larly (regular) than in the effect of being encouraged to watch Sesame Street. Fit an appropriate model to answer this question.
e. Comment on which of the two previous estimates can plausibly be interpreted causally.